spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# JWT
app.jwt.secret=${APP_JWT_SECRET:ChangeThisToASecretKeyWithAtLeast32Chars}
app.jwt.expiration-minutes=${APP_JWT_EXPIRATION_MINUTES:1440}
